name: Build Image
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Login into Github Docker Registery
          run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

        - name: Install Shopware-CLI
          uses: FriendsOfShopware/shopware-cli-action@v1

        - name: Make image name small
          id: image
          run: |
            export "name=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest"
            echo "image=${name,,}" >> ${GITHUB_OUTPUT}

        - name: Cache Composer
          id: cache-composer-files
          uses: actions/cache@v3
          with:
            path: composer-cache-files
            key: composer-cache-${{ hashFiles('composer.lock') }}

        - name: Inject Cache
          uses: reproducible-containers/buildkit-cache-dance@v2.1.4
          with:
            cache-source: composer-cache-files
            cache-target: /root/.composer
            skip-extraction: ${{ steps.cache-composer-files.outputs.cache-hit }}

        - name: Generate image
          run: shopware-cli project docker build ${{ steps.image.outputs.image }} --generate-only

        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: ${{ steps.image.outputs.image }}
